"""empty message

Revision ID: 0730b10249c2
Revises: b5f92725af9d
Create Date: 2020-05-23 17:45:41.553505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0730b10249c2'
down_revision = 'b5f92725af9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='product')
    op.drop_index('price', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('price', 'product', ['price'], unique=True)
    op.create_index('name', 'product', ['name'], unique=True)
    # ### end Alembic commands ###
